### PR TITLE
DPWEBCORE-909: split slow rules

### PR DESCRIPTION
**Pull request by benwainwright**
One of the side effects to adding more eslint rules is that some of them are necessarily quite slow. The below table is taken from profiling the slowest rules in our ruleset when run against `bbc/status`

image

You can see that the bulk of the time is taken by two rules from the `import` plugin. Here is the same table after locally installing our shared config into `webcore-pipelines` and running it (we should install it properly soon to try to unify our estate).

image

Same two at the top of the chart, but this time `import/no-cycle` is 4 times as slow as it was before. This is clearly at least linearly slowing down as the codebase gets bigger, and will only get worse. 

Note; that although these rules are slow, they are still valuable, but I'm proposing we don't run the slowest rules during commit hooks, because although there is tonnes of value in blocking commits when linting rules fail, if we slow down commits horrendously when doing so, it's just going to become painful.

This PR splits the slowest rules into a second config. We can explicitly use this config in a separate yarn script that is NOT run by the commit hooks, but can be run on demand and will definitely be run by CI.

### CODE REVIEW

**Comment by jameshd** [comment]
Hey, I'm just curious if running these on every commit is excessive which I think you said you do? I'm not actively writing code so only offering guidance here. 

Couple of thoughts: 
1. Can your editor not be picking up linting errors as you're working? 
2. Would running them pre-push not have the same overall effect? 

I apprecaite you don't want bad commits getting into the codebase, but if you're waiting for these rules to finish after every commit (or now working around these rules), that's gonna be slowing you down considerably and there will be times when you forgot to run these slower rules and it breaks on CI instead causing yet more delays. I'd rather see a single commit that "fixes linting errors" and changes be released quicker. 

Proposal:
Keep these rules but run linting checks pre-push enabling you to commit frequently locally and lint once before pushing to master. Failing that, set constraints such as `maxDepth:3` and switch on `ignoreExternal`to avoid checking external deps.

**Comment by benwainwright** [comment]
> Can your editor not be picking up Linting errors as you're working?

Well yes. But that depends on every dev setting up their editor correctly. Using commit hooks provides a near-guarantee that you simply *can't* get bad code into the codebase.

> Would running them pre-push not have the same overall effect?

No; running them pre-push would mean that if they fail you'd have to either

1. Rebase your branch to remove the bad commits (something not everyone is confident doing)
2. Introduce commits to remove the failing code. As you say; the "single commit" approach.

Here are the benefits to blocking bad commits as I see them:

- When the project becomes big enough that you might need to do a "git bisect", this becomes easier if all commits are green; though this admittedly applies more to tests. An alternative approach to this is to force squash merges; but that does lose some granularity in the commit history.
- You have quite rightly pointed out that people can set up their editors to highlight these issues. Forcing them to be fixed before commit will mean people will probably make sure that this is correctly configured, and will address them as a matter of course. The "Fixed linting errors" commit only becomes a thing if they *don't* do that.
-  It encourages good git practise: check speed will increase as a function of the number of files included in the commit. This will encourage more atomic commits, which can be helpful when you want to revert changes, will likely lead to more descriptive commit messages (ever used the commit message 'done some stuff' because there is 100+ changes in your commit? I certainly have in hobby projects), and is useful in code reviews sometimes when you want to dig into the process behind what a person has done.
- It encourages us to be more mindful of writing isolated unit tests where possible.

I fully appreciate that this is a little controversial. But I'd argue that in summary:

* It has benefits (see above)
* It is not *currently* causing a problem
* It is trivial to switch to an alternative approach regardless of how complicated the codebase is

I'd like to see how this plays out. I'm fully open to the idea of switching to a different approach *when it becomes a pain*. But we aren't there yet, so lets give it a go.

I'd really be interested in opinions on this from other quarters

@MattLongCode @BogdanDogaru @abrarkhan1234

**Comment by benwainwright** [comment]
@MattLongCode @jameshd is questioning here whether the whole thing is necessary though?

**Comment by jameshd** [comment]
@benwainwright @MattLongCode 

> is questioning here whether the whole thing is necessary though?

I'm asking if it's better to run all the linting rules, but only once, pre-push and then once on CI. Not every commit because it's slow...

**Comment by benwainwright** [comment]
@jameshd Sorry, yes. That's what I meant.

**Comment by jameshd** [comment]
In the interests of keeping things moving. Merge this - we'll revisit if it becomes a problem

**Pull request merged**
